version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
    restart: always
    hostname: chat
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_MULTIPLE_DATABASES=chat,chat_test

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080/tcp"
    volumes:
      - .:/app
